### ISSUE TITLE
Release of code

### ISSUE THREAD

**Issue by itsmag11** [sail-sg/finetune-fair-diffusion#1]
Dear authors of "Finetuning Text-to-Image Diffusion Models for Fairness",

Congratulations on the acceptance as an ICLR 2024 oral paper. It is truly an excellent and insightful work. Your contribution to the domain of fairness in diffusion models is greatly appreciated. I would like to inquire about the expected code release date, if possible. Thank you in advance for your response.

**Comment by XudongOliverShen** [comment]
Hello, thank you very much for your interest in our work! I apologize for the delay on my end. I will share the code and checkpoints before March 1st.

**Comment by zahraaalsahili** [comment]
any updates?

**Comment by XudongOliverShen** [comment]
Hello, @zahraaalsahili  I am currently working on it and can provide an updated release date as March 10. Apologies for the delay... I was overwhelmed with other responsibilities...

**Comment by XudongOliverShen** [comment]
Hi everyone, I've just uploaded the code and checkpoints. My apologies for the delay. I'm going to close this issue now, but please don't hesitate to open new ones if anything remains unclear. :)
